In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3,4])
a,type(a)

(array([1, 2, 3, 4]), numpy.ndarray)

In [18]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b[1,1])

[[1 2 3]
 [4 5 6]]
5


In [19]:
# numpy.shape
print(a.shape)
print(b.shape)  # .shape returns (number of elements in the array, number of values in each elements)

(4,)
(2, 3)


### 初始化array

In [22]:
# numpy.zeros
a = np.zeros([2,3]) 
print(a,a.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [24]:
# numpy.ones*()
b = np.ones(3)
print(b)

[1. 1. 1.]


In [26]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


### 对角矩阵 

np.eye : Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [30]:
d = np.eye(10)

In [31]:
print(d)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [32]:
# numpy.random.random
e = np.random.random((2,2))

In [33]:
print(e)

[[0.18555981 0.93922737]
 [0.96520055 0.68285222]]


## array math

In [37]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [38]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [39]:
print(x+y)

[[ 6  8]
 [10 12]]


In [40]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [41]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [42]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [133]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [137]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [138]:
print(np.divide(x,y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [141]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [142]:
print((np.sqrt(x))**2)

[[ 1.  2.]
 [ 3.  4.]]


In [46]:
v = np.array([1,2])
w = np.array([3,4])

In [47]:
print(v.dot(w))

11


In [48]:
print('x=\n',x,'\n','y=\n',y)

x=
 [[1 2]
 [3 4]] 
 y=
 [[5 6]
 [7 8]]


In [51]:
print(y.T)

[[5 7]
 [6 8]]


### np.sum

In [55]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
print(np.sum(x))

21


In [59]:
print(np.sum(x,axis=0)) #每列 列和

[ 9 12]


In [60]:
print(np.sum(x,axis=1)) #每行 行和

[ 3  7 11]


### Numpy提供的创建数组的函数 arange：
---
##### 这个函数返回ndarray对象，包含给定范围内的等间隔值。
---
##### numpy.arange(start, stop, step, dtype)

In [160]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(1,10,2,dtype=int)

array([1, 3, 5, 7, 9])