In [1]:
import numpy

In [16]:
a = numpy.array([1,2,3,4])

In [17]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [121]:
import numpy as np

In [7]:
b = np.array([1,2,3])

In [8]:
print(b)

[1 2 3]


In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [10]:
# numpy.shape
print(a.shape)

(3,)


In [11]:
print(b.shape)

(3,)


In [18]:
print(a[-1])

4


In [19]:
print(a[2])

3


In [20]:
print(a)

[1 2 3 4]


In [21]:
print(a[1])

2


In [22]:
a[1] = 5

In [23]:
print(a[1])

5


In [24]:
print(a)

[1 5 3 4]


In [25]:
b = np.array([[1,2,3],[4,5,6]])

In [26]:
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
print(type(b))

<class 'numpy.ndarray'>


In [28]:
print(b.shape)

(2, 3)


In [30]:
print(b[1,1])

5


In [31]:
# numpy.zeros
a = np.zeros(2)

In [32]:
print(a)

[ 0.  0.]


In [33]:
print(a.shape)

(2,)


In [37]:
a = np.zeros([2,3])

In [38]:
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [39]:
print(a.shape)

(2, 3)


In [40]:
# numpy.ones*()
b = np.ones(3)

In [41]:
print(b)

[ 1.  1.  1.]


In [44]:
b = np.ones((3,3))

In [45]:
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [46]:
c = np.full((2,2),7)

In [47]:
print(c)

[[7 7]
 [7 7]]


In [48]:
d = np.eye(10)

In [49]:
print(d)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [52]:
# numpy.random.random
e = np.random.random((2,2))

In [53]:
print(e)

[[ 0.26665006  0.00849483]
 [ 0.96262301  0.725559  ]]


In [54]:
e = np.random.random((2,2))
print(e)

[[ 0.92653932  0.54838782]
 [ 0.88271239  0.88818265]]


In [55]:
e = np.random.random((2,2))
print(e)

[[ 0.96130664  0.08758942]
 [ 0.8246749   0.06755322]]


In [57]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,13]])

In [58]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 13]]


In [59]:
print(a[0:2,0:2])

[[1 2]
 [5 6]]


In [60]:
b = np.array([1,2,3,4,5])

In [61]:
print(b[1:3])

[2 3]


In [62]:
print(b[1:])

[2 3 4 5]


In [63]:
print(b[:3])

[1 2 3]


In [66]:
print(b[::2])

[1 3 5]


In [67]:
print(b[1::2])

[2 4]


In [68]:
c = np.array([1,2,4])

In [69]:
print(c)

[1 2 4]


In [70]:
print(b[c])

[2 3 5]


In [71]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 13]]


In [72]:
a_1 = a[1,:]

In [73]:
print(a_1,a_1.shape)

[5 6 7 8] (4,)


In [79]:
print(a_1[0])

5


In [77]:
print(a_1.ndim)

1


In [74]:
a_2 = a[1:2,:]

In [75]:
print(a_2,a_2.shape)

[[5 6 7 8]] (1, 4)


In [76]:
print(a_2.ndim)

2


In [78]:
print(a_2[0])

[5 6 7 8]


In [86]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 13]]


In [87]:
print(a[[0,1,2],[1,2,0]])

[2 7 9]


In [92]:
print(np.array([a[0,1],a[1,2],a[2,0]]))

[2 7 9]


In [93]:
c = np.array([0,1,2])

In [94]:
d = np.array([1,2,0])

In [95]:
print(a[c,d])

[2 7 9]


In [96]:
bool_idx = (a>5)

In [97]:
print(bool_idx)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [98]:
print(a[bool_idx])

[ 6  7  8  9 10 11 13]


In [99]:
print(a[bool_idx].shape)

(7,)


In [101]:
print(a[a>5])

[ 6  7  8  9 10 11 13]


In [107]:
a = np.array([1,2])

In [108]:
print(a)

[1 2]


In [109]:
print(a.dtype)

int32


In [110]:
a = np.array([1.0,2.0])

In [111]:
print(a)

[ 1.  2.]


In [112]:
print(a.dtype)

float64


In [117]:
a = np.array([1.0,2.6],dtype = complex)

In [118]:
print(a)

[ 1.0+0.j  2.6+0.j]


In [122]:
# arrary math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [124]:
print(x,'\n',y)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [125]:
print(x+y)

[[ 6  8]
 [10 12]]


In [126]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [130]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [131]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [136]:
print(x**y)

[[    1    64]
 [ 2187 65536]]


In [133]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [137]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [138]:
print(np.divide(x,y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [141]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [142]:
print((np.sqrt(x))**2)

[[ 1.  2.]
 [ 3.  4.]]


In [143]:
v = np.array([1,2])
w = np.array([3,4])

In [144]:
print(v.dot(w))

11


In [145]:
print(np.dot(v,w))

11


In [146]:
print(x.dot(v))

[ 5 11]


In [147]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [148]:
print('x=\n',x,'\n','y=\n',y)

x=
 [[1 2]
 [3 4]] 
 y=
 [[5 6]
 [7 8]]


In [149]:
print(x.T)

[[1 3]
 [2 4]]


In [150]:
print(v.T)

[1 2]


In [151]:
v2 = v.T

In [152]:
print(v2.shape)

(2,)


In [153]:
print(np.sum(x))

10


In [154]:
print(np.sum(x,axis=0))

[4 6]


In [155]:
print(np.sum(x,axis=1))

[3 7]


### Numpy提供的创建数组的函数 arange：
---
##### 这个函数返回ndarray对象，包含给定范围内的等间隔值。
---
##### numpy.arange(start, stop, step, dtype)

In [160]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(1,10,2,dtype=int)

array([1, 3, 5, 7, 9])

### Numpy提供的创建数组的函数 linspace:
---
##### 此函数类似于arange()函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长。 此函数的用法如下。
---
##### numpy.linspace(start, stop, num, endpoint, retstep, dtype)

In [164]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [165]:
np.linspace(0,10,10,endpoint=False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [166]:
np.linspace(0,9,10)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### Numpy提供的创建数组的函数 logspace:
---
#### 此函数返回一个ndarray对象，其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。
---
#### numpy.logspace(start, stop, num, endpoint, base, dtype)

In [171]:
np.logspace(1,10,10)

array([  1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05,   1.00000000e+06,
         1.00000000e+07,   1.00000000e+08,   1.00000000e+09,
         1.00000000e+10])

In [172]:
np.logspace(1,10,10,base=2)

array([    2.,     4.,     8.,    16.,    32.,    64.,   128.,   256.,
         512.,  1024.])

END